/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ToastParams {
  title?: string
  text1: string
  text2?: string
}
export function noti(not: ToastParams): boolean
