/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const POWERSHELL_APP_ID: string
export interface ToastParams {
  text1?: string
  text2: string
  text3?: string
}
export type JsToaster = Toaster
export class Toaster {
  constructor(appId?: string | undefined | null)
  noti(not: ToastParams): boolean
}
